%YAML 1.1

---

$schema: 'https://json-schema.org/draft/2020-12/schema'

title: |
  'Delomaten' configuration data

type: object
required:
  - shared_bucket
  - source_folder
  - destination_folder
  - memory_size
  - pseudo
properties:

  shared_bucket:
    description: |
      The name of the shared bucket
    type: string

  source_folder:
    description: |
      The folder prefix inside the teams' product bucket from which
      to fetch the files
    type: string
    pattern: "(^([a-zA-Z0-9])[/a-zA-Z0-9]+[a-zA-Z0-9]$|^[a-zA-Z]*$)"
    errorMessage:
      pattern: |
        Validation error in 'source_folder' property. Folder prefixes cannot begin or end with a '/' character
        and can otherwise only contain alphanumerical characters

  destination_folder:
    description: |
      The folder prefix inside the shared bucket from which
      to write the processed files to
    type: string
    pattern: "(^([a-zA-Z0-9])[/a-zA-Z0-9]+[a-zA-Z0-9]$|^[a-zA-Z]*$)"
    errorMessage:
      pattern: |
          Validation error in 'source_folder' property. Folder prefixes cannot begin or end with a '/' character
          and can otherwise only contain alphanumerical characters

  memory_size:
    description: |
      The amount of memory in GiB given to the data automation processor instance
    type: integer
    minimum: 1

  output_columns:
    description: |
      The columns to be outputted when writing the result to the shared bucket.
      If 'output_columns' isn't specified all columns are outputted.
    type: array
    minItems: 1
    items:
      type: string
    errorMessage:
      minItems: |
        Validation error in 'output_columns'. The array must contain at least one element.

  pseudo:
    description: |
      The pseudonymization tasks to be run
    type: array
    minItems: 1
    errorMessage:
      minItems: |
        Validation error in 'output_columns'. The array must contain at least one element.
    items:
      type: object
      required:
        - name
        - columns
        - pseudo_operation
        - encryption_algorithm

      properties:
        name:
          description: |
            A name describing the pseudo task
          type: string
          minLength: 3

        columns:
          description: |
            Which columns in the dataframe to target
          type: array
          minItems: 1
          errorMessage:
            minItems: |
              Validation error in 'columns'. The array must contain at least one element.
          items:
            type: string

        pseudo_operation:
          description: |
            What pseudo operation to apply to the targets
          enum:
            - "PSEUDO"
            - "DEPSEUDO"
            - "REPSEUDO"

        encryption_algorithm:
          description: |
            What type of encryption to use
          enum:
            - "default"
            - "papis_compatible"
            - "sid_mapping"
            - "redact"

        encryption_args:
          description: |
            Any additional arguments to pass to the encryption algorithm
          type: array
          items:
            type: string
