name: Test delomaten config schema validity

on:
  push:
    branches:
      - main
    paths:
      - 'schema-validation/**'
      - 'generate/**'
      - 'validate/**'
      - 'build.mill'
      - 'flake8conf'
      - '.scalafmt.conf'
      - '.github/workflows/test-schema-validity.yaml'
  pull_request:
    paths:
      - 'schema-validation/**'
      - 'generate/**'
      - 'validate/**'
      - 'build.mill'
      - 'flake8conf'
      - '.scalafmt.conf'
      - '.github/workflows/test-schema-validity.yaml'

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  run-delomaten-schema-tests:
    name: Run schema validity tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache mill
        uses: actions/cache@v4
        with:
          path: ~/.cache/mill/download
          key: ${{ runner.os }}-mill-download-cache
      - uses: coursier/cache-action@v6.4.7
      - uses: coursier/setup-action@v1.3.9
        with:
          jvm: zulu:21.0.7
      - name: Setup coursier credentials
        run: |
          mkdir -p ~/.config/coursier
          cat <<EOF > ~/.config/coursier/credentials.properties
          simple.username=${{ github.actor }}
          simple.password=${{ secrets.GITHUB_TOKEN }}
          simple.host=maven.pkg.github.com
          EOF
      - name: Scala code formatting check
        run: |
          ./mill mill.scalalib.scalafmt/checkFormat || (
            echo "To format code run"
            echo "  mill mill.scalalib.scalafmt/reformat "
            exit 1
          )
      - name: Run schema validation tests
        run: |
          ./mill validate.test
  run-delomaten-codegen-tests:
    name: Run code generation tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache mill
        uses: actions/cache@v4
        with:
          path: ~/.cache/mill/download
          key: ${{ runner.os }}-mill-download-cache
      - uses: coursier/cache-action@v6.4.7
      - uses: coursier/setup-action@v1.3.9
        with:
          jvm: zulu:21.0.7
      - name: Setup coursier credentials
        run: |
          mkdir -p ~/.config/coursier
          cat <<EOF > ~/.config/coursier/credentials.properties
          simple.username=${{ github.actor }}
          simple.password=${{ secrets.GITHUB_TOKEN }}
          simple.host=maven.pkg.github.com
          EOF
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install flake8
        shell: bash
        run: |
          python -m pip install --upgrade flake8
      - name: Test generating python code from valid YAML configurations
        run: |
          ./mill generate.test
