name: Test delomaten config schema validity

on:
  push:
    branches:
      - main
    paths:
      - 'scripts'
      - '.github/workflows/test-schema-validity.yaml'
  pull_request:
    paths:
      - 'scripts'
      - '.github/workflows/test-schema-validity.yaml'

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  run-delomaten-schema-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.5.18'
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      # Test that the schema itself is valid
      - name: Run schema meta tests
        shell: bash
        run: |
          uv run pytest -v
      - name: Run schema unit tests
        shell: bash
        run: |
          cd scripts
          uv run pytest -v test/main.py
