name: Test delomaten config schema validity

on:
  push:
    branches:
      - main
    paths:
      - 'schema-validation/**'
      - '.github/workflows/test-schema-validity.yaml'
  pull_request:
    paths:
      - 'schema-validation/**'
      - '.github/workflows/test-schema-validity.yaml'

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  run-delomaten-schema-tests:
    name: Run schema validity tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v18
      - name: Use Nix development shell
        uses: nicknovitski/nix-develop@v1.2.1
      - name: Scala code formatting check
        run: |
          mill mill.scalalib.scalafmt/checkFormat || (
            echo "To format code run"
            echo "  mill mill.scalalib.scalafmt/reformat "
            exit 1
          )
      - name: Run schema validation tests
        run: |
          mill validate.test
  run-delomaten-codegen-tests:
    name: Run code generation tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v18
      - name: Use Nix development shell
        uses: nicknovitski/nix-develop@v1.2.1
      - name: Test generating python code from valid YAML configurations
        run: |
          mill generate.test
